services:
  server:
    build:
      context: .
    env_file:
      - .env
  
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db


volumes:
  mongodb_data:

